name: verify
on: [pull_request]
defaults:
  run:
    shell: bash
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm prettier
      - run: pnpm build
